#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := TEF_Animation_Example

# EXTRA_COMPONENT_DIRS := $(XASCODE_PATH)/ESP32

EXTRA_COMPONENT_DIRS := tef-synth-animation/esp-synth-animation tef-led-magic/esp-led-magic

include $(IDF_PATH)/make/project.mk
